/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package SMMV.OL.gui;

import SMMV.Connection.connection_ol;
import SMMV.Main.Dashboard_ol;
import SMMV.OL.form.Student;
import java.util.HashMap;
import java.util.Vector;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class OL_Subject extends javax.swing.JDialog {

    Dashboard_ol dashboard;
    Student student;
        DefaultTableModel tablemodel;

    String languageID;
    String religionId;
    String icategory;
    String iicategory;
    String iiicategory;
    String englishId;
    String mathsId;
    String scienceId;
    String historyId;

    public JCheckBox getAosinhala() {
        return aosinhala;
    }

    public JCheckBox getArt() {
        return art;
    }

    public JCheckBox getBuddist() {
        return buddist;
    }

    public JCheckBox getBussness() {
        return bussness;
    }

    public JCheckBox getCatholicm() {
        return catholicm;
    }

    public JCheckBox getChristianity() {
        return christianity;
    }

    public JCheckBox getCivic() {
        return civic;
    }

    public JCheckBox getDanceb() {
        return danceb;
    }

    public JCheckBox getDanceo() {
        return danceo;
    }

    public JCheckBox getDrama() {
        return drama;
    }

    public JCheckBox getEconomic() {
        return economic;
    }

    public JCheckBox getEntrepreneurship() {
        return entrepreneurship;
    }

    public JCheckBox getFrench() {
        return french;
    }

    public JCheckBox getGeogra() {
        return geogra;
    }

    public JCheckBox getGermen() {
        return germen;
    }

    public JCheckBox getHealth() {
        return health;
    }

    public JCheckBox getIct() {
        return ict;
    }

    public JCheckBox getIslam() {
        return islam;
    }

    public JCheckBox getJapan() {
        return japan;
    }

    public JCheckBox getKarean() {
        return karean;
    }

    public JCheckBox getMusico() {
        return musico;
    }

    public JCheckBox getMusicw() {
        return musicw;
    }

    public JCheckBox getPali() {
        return pali;
    }

    public JCheckBox getSaivanery() {
        return saivanery;
    }

    public JCheckBox getSanskrit() {
        return sanskrit;
    }

    public JCheckBox getSecond() {
        return second;
    }

    public JCheckBox getSecont2() {
        return secont2;
    }

    public JCheckBox getSinhala() {
        return sinhala;
    }

    public JCheckBox getTamil() {
        return tamil;
    }

    public JCheckBox getEnglish() {
        return english;
    }

    public JCheckBox getHistory() {
        return history;
    }

    public JCheckBox getMathematics() {
        return mathematics;
    }

    public JCheckBox getScience() {
        return science;
    }
    /**
     * Creates new form OL_Subject
     */
    public OL_Subject(java.awt.Frame parent, boolean modal, Student student) {
        super(parent, modal);
        initComponents();
        dashboard = (Dashboard_ol) parent;
        this.student = student;
        english.setSelected(true);
        science.setSelected(true);
        history.setSelected(true);
        mathematics.setSelected(true);
        tablemodel  = (DefaultTableModel) student.getOlTable().getModel();
        tablemodel.setRowCount(0);
    }


    
    private void subjectName(String subjectId) {
        try {
            

            Vector subjectVector = new Vector();
            ResultSet rs = connection_ol.search("SELECT * FROM `subject` WHERE `subject_id`='" + subjectId + "'");

            while (rs.next()) {

                subjectVector.add(subjectId);
                subjectVector.add(rs.getString("subject_name"));

            }
            tablemodel.addRow(subjectVector);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        background1 = new SMMV.Component.Background();
        jLabel27 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        background2 = new SMMV.Component.Background();
        jLabel28 = new javax.swing.JLabel();
        english = new javax.swing.JCheckBox();
        mathematics = new javax.swing.JCheckBox();
        history = new javax.swing.JCheckBox();
        science = new javax.swing.JCheckBox();
        background3 = new SMMV.Component.Background();
        sinhala = new javax.swing.JCheckBox();
        tamil = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        buddist = new javax.swing.JCheckBox();
        saivanery = new javax.swing.JCheckBox();
        catholicm = new javax.swing.JCheckBox();
        christianity = new javax.swing.JCheckBox();
        islam = new javax.swing.JCheckBox();
        background4 = new SMMV.Component.Background();
        jLabel31 = new javax.swing.JLabel();
        bussness = new javax.swing.JCheckBox();
        civic = new javax.swing.JCheckBox();
        geogra = new javax.swing.JCheckBox();
        entrepreneurship = new javax.swing.JCheckBox();
        second = new javax.swing.JCheckBox();
        secont2 = new javax.swing.JCheckBox();
        pali = new javax.swing.JCheckBox();
        sanskrit = new javax.swing.JCheckBox();
        french = new javax.swing.JCheckBox();
        germen = new javax.swing.JCheckBox();
        japan = new javax.swing.JCheckBox();
        karean = new javax.swing.JCheckBox();
        musico = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        musicw = new javax.swing.JCheckBox();
        danceo = new javax.swing.JCheckBox();
        danceb = new javax.swing.JCheckBox();
        aosinhala = new javax.swing.JCheckBox();
        drama = new javax.swing.JCheckBox();
        art = new javax.swing.JCheckBox();
        jLabel33 = new javax.swing.JLabel();
        ict = new javax.swing.JCheckBox();
        economic = new javax.swing.JCheckBox();
        health = new javax.swing.JCheckBox();
        buttonGradient4 = new SMMV.Component.ButtonGradient();
        buttonGradient5 = new SMMV.Component.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Select Grade 10 & 11 Subject");

        jSeparator1.setForeground(new java.awt.Color(0, 255, 255));

        background2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 255, 255));
        jLabel28.setText("Importan Subject");

        english.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        english.setText("English");

        mathematics.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        mathematics.setText("Mathematics");

        history.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        history.setText("History");

        science.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        science.setText("Science");

        javax.swing.GroupLayout background2Layout = new javax.swing.GroupLayout(background2);
        background2.setLayout(background2Layout);
        background2Layout.setHorizontalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background2Layout.createSequentialGroup()
                        .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(english)
                            .addComponent(science))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mathematics, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(history))
                        .addGap(15, 15, 15))
                    .addGroup(background2Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        background2Layout.setVerticalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(english)
                    .addComponent(mathematics))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(history)
                    .addComponent(science))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        english.setActionCommand("2");
        mathematics.setActionCommand("3");
        history.setActionCommand("9");
        science.setActionCommand("4");

        background3.setBackground(new java.awt.Color(0, 0, 0));

        buttonGroup1.add(sinhala);
        sinhala.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        sinhala.setText(" Sinhala Language & Literature");

        buttonGroup1.add(tamil);
        tamil.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tamil.setText("Tamil Language & Literature");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 255, 255));
        jLabel29.setText("Language & Literature");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 255, 255));
        jLabel30.setText("Religion");

        buttonGroup2.add(buddist);
        buddist.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buddist.setText("Buddhism");

        buttonGroup2.add(saivanery);
        saivanery.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        saivanery.setText("Saivanery");

        buttonGroup2.add(catholicm);
        catholicm.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        catholicm.setText("Catholicism");

        buttonGroup2.add(christianity);
        christianity.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        christianity.setText("Christianity");

        buttonGroup2.add(islam);
        islam.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        islam.setText("Islam");

        javax.swing.GroupLayout background3Layout = new javax.swing.GroupLayout(background3);
        background3.setLayout(background3Layout);
        background3Layout.setHorizontalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background3Layout.createSequentialGroup()
                        .addGroup(background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(catholicm)
                            .addGroup(background3Layout.createSequentialGroup()
                                .addComponent(saivanery)
                                .addGap(26, 26, 26)
                                .addComponent(islam))
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tamil)
                            .addComponent(sinhala)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(background3Layout.createSequentialGroup()
                        .addComponent(buddist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(christianity)
                        .addGap(16, 16, 16))))
        );
        background3Layout.setVerticalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sinhala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tamil)
                .addGap(18, 18, 18)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buddist)
                    .addComponent(christianity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saivanery)
                    .addComponent(islam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(catholicm)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        sinhala.setActionCommand("1");
        tamil.setActionCommand("11");
        buddist.setActionCommand("5");
        saivanery.setActionCommand("19");
        catholicm.setActionCommand("21");
        christianity.setActionCommand("18");
        islam.setActionCommand("20");

        background4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 255, 255));
        jLabel31.setText("I Category Subject (Please select one subject)");

        buttonGroup3.add(bussness);
        bussness.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bussness.setText("Business & Accounting Studies");

        buttonGroup3.add(civic);
        civic.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        civic.setText(" Civic Education");

        buttonGroup3.add(geogra);
        geogra.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        geogra.setText("Geography");

        buttonGroup3.add(entrepreneurship);
        entrepreneurship.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        entrepreneurship.setText("Entrepreneurship Studies");

        buttonGroup3.add(second);
        second.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        second.setText("Second Language (Sinhala)");

        buttonGroup3.add(secont2);
        secont2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        secont2.setText("Second Language (Tamil)");

        buttonGroup3.add(pali);
        pali.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pali.setText("Pali");

        buttonGroup3.add(sanskrit);
        sanskrit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        sanskrit.setText("Sanskrit");

        buttonGroup3.add(french);
        french.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        french.setText(" French");

        buttonGroup3.add(germen);
        germen.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        germen.setText("German");

        buttonGroup3.add(japan);
        japan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        japan.setText("Japanese");

        buttonGroup3.add(karean);
        karean.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        karean.setText(" Korean");

        buttonGroup4.add(musico);
        musico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        musico.setText(" Music (Oriental)");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 255, 255));
        jLabel32.setText("II Category Subject (Please select one subject)");

        buttonGroup4.add(musicw);
        musicw.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        musicw.setText("Music (Western)");

        buttonGroup4.add(danceo);
        danceo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        danceo.setText("Dancing (Oriental)");

        buttonGroup4.add(danceb);
        danceb.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        danceb.setText(" Dancing (Bharata)");

        buttonGroup4.add(aosinhala);
        aosinhala.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        aosinhala.setText("Appreciation of Sinhala Literary Texts");

        buttonGroup4.add(drama);
        drama.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        drama.setText("Drama and Theatre (Sinhala)");

        buttonGroup4.add(art);
        art.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        art.setText("Art");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 255, 255));
        jLabel33.setText("IIi Category Subject (Please select one subject)");

        buttonGroup5.add(ict);
        ict.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ict.setText("Information & Communication Technology");

        buttonGroup5.add(economic);
        economic.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        economic.setText("Home Economics");

        buttonGroup5.add(health);
        health.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        health.setText("Health & Physical Education");

        javax.swing.GroupLayout background4Layout = new javax.swing.GroupLayout(background4);
        background4.setLayout(background4Layout);
        background4Layout.setHorizontalGroup(
            background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background4Layout.createSequentialGroup()
                        .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(background4Layout.createSequentialGroup()
                                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bussness)
                                    .addComponent(entrepreneurship)
                                    .addComponent(secont2)
                                    .addComponent(germen))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(civic)
                                    .addComponent(second)
                                    .addComponent(sanskrit)
                                    .addComponent(japan))
                                .addGap(20, 20, 20)
                                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(karean)
                                    .addComponent(french)
                                    .addComponent(pali)
                                    .addComponent(geogra))))
                        .addContainerGap())
                    .addGroup(background4Layout.createSequentialGroup()
                        .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(danceb)
                            .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(musico)
                                .addComponent(danceo)))
                        .addGap(79, 79, 79)
                        .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(background4Layout.createSequentialGroup()
                                .addComponent(musicw)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(art)
                                .addGap(54, 54, 54))
                            .addGroup(background4Layout.createSequentialGroup()
                                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aosinhala)
                                    .addComponent(drama))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(background4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ict)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(background4Layout.createSequentialGroup()
                                .addComponent(economic)
                                .addGap(94, 94, 94)
                                .addComponent(health)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        background4Layout.setVerticalGroup(
            background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bussness)
                    .addComponent(civic)
                    .addComponent(geogra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entrepreneurship)
                    .addComponent(second)
                    .addComponent(pali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secont2)
                    .addComponent(sanskrit)
                    .addComponent(french))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(germen)
                    .addComponent(japan)
                    .addComponent(karean))
                .addGap(18, 18, 18)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musico)
                    .addComponent(musicw)
                    .addComponent(art))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(danceo)
                    .addComponent(aosinhala))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drama)
                    .addComponent(danceb))
                .addGap(18, 18, 18)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ict)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(economic)
                    .addComponent(health))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bussness.setActionCommand("22");
        civic.setActionCommand("6");
        geogra.setActionCommand("12");
        entrepreneurship.setActionCommand("23");
        second.setActionCommand("24");
        secont2.setActionCommand("26");
        pali.setActionCommand("25");
        sanskrit.setActionCommand("27");
        french.setActionCommand("28");
        germen.setActionCommand("29");
        japan.setActionCommand("30");
        karean.setActionCommand("31");
        musico.setActionCommand("32");
        musicw.setActionCommand("33");
        danceo.setActionCommand("34");
        danceb.setActionCommand("35");
        aosinhala.setActionCommand("36");
        drama.setActionCommand("37");
        art.setActionCommand("16");
        ict.setActionCommand("7");
        economic.setActionCommand("38");
        health.setActionCommand("8");

        buttonGradient4.setText("OK");
        buttonGradient4.setColor1(new java.awt.Color(0, 0, 204));
        buttonGradient4.setColor2(new java.awt.Color(139, 139, 252));
        buttonGradient4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonGradient4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient4ActionPerformed(evt);
            }
        });

        buttonGradient5.setText("Cancel");
        buttonGradient5.setColor1(new java.awt.Color(0, 0, 204));
        buttonGradient5.setColor2(new java.awt.Color(139, 139, 252));
        buttonGradient5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonGradient5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(background2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(background3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(background4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(background1Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonGradient5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonGradient4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGradient4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGradient5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(background2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(background3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(background4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGradient4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient4ActionPerformed
        // TODO add your handling code here:
        boolean english_check = english.isSelected();
        boolean maths_check = mathematics.isSelected();
        boolean science_check = science.isSelected();
        boolean history_check = history.isSelected();

        boolean sinhala_check = sinhala.isSelected();
        boolean tamil_check = tamil.isSelected();

        boolean buddism_check = buddist.isSelected();
        boolean christianity_check = christianity.isSelected();
        boolean saivanery_check = saivanery.isSelected();
        boolean catalic_check = catholicm.isSelected();
        boolean islam_check = islam.isSelected();

        //I Category
        boolean business_check = bussness.isSelected();
        boolean civic_check = civic.isSelected();
        boolean geography_check = geogra.isSelected();
        boolean entership_check = entrepreneurship.isSelected();
        boolean secondS_check = second.isSelected();
        boolean secondT_check = secont2.isSelected();
        boolean pali_check = pali.isSelected();
        boolean sanskrit_check = sanskrit.isSelected();
        boolean french_check = french.isSelected();
        boolean german_check = germen.isSelected();
        boolean japan_check = japan.isSelected();
        boolean korean_check = karean.isSelected();

        //II Catrgory
        boolean musicO_check = musico.isSelected();
        boolean musicW_check = musicw.isSelected();
        boolean danceO_check = danceo.isSelected();
        boolean danceB_check = danceb.isSelected();
        boolean aosinhala_check = aosinhala.isSelected();
        boolean drama_check = drama.isSelected();
        boolean art_check = art.isSelected();

        //III Category
        boolean ict_check = ict.isSelected();
        boolean home_check = economic.isSelected();
        boolean health_check = health.isSelected();

        if (!english_check) {
            JOptionPane.showMessageDialog(this, "Please Select English Subject", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!maths_check) {
            JOptionPane.showMessageDialog(this, "Please Select Mathematics Subject", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!history_check) {
            JOptionPane.showMessageDialog(this, "Please Select History Subject", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!science_check) {
            JOptionPane.showMessageDialog(this, "Please Select Science Subject", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!sinhala_check && !tamil_check) {
            JOptionPane.showMessageDialog(this, "Please Select Language & Literature Subject", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!buddism_check && !christianity_check && !catalic_check && !saivanery_check && !islam_check) {
            JOptionPane.showMessageDialog(this, "Please Select Religion Subject", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!business_check && !civic_check && !geography_check && !entership_check && !secondS_check
                && !secondT_check && !pali_check && !sanskrit_check && !french_check && !german_check
                && !japan_check && !korean_check) {
            JOptionPane.showMessageDialog(this, "Please Select First Category Subject", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!musicO_check && !musicW_check && !danceO_check && !danceB_check && !aosinhala_check && !drama_check && !art_check) {
           JOptionPane.showMessageDialog(this, "Please Select Second Category Subject", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!ict_check && !home_check && !health_check) {
            JOptionPane.showMessageDialog(this, "Please Select Thurd Category Subject", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            languageID = buttonGroup1.getSelection().getActionCommand();
            religionId = buttonGroup2.getSelection().getActionCommand();
            icategory = buttonGroup3.getSelection().getActionCommand();
            iicategory = buttonGroup4.getSelection().getActionCommand();
            iiicategory = buttonGroup5.getSelection().getActionCommand();
            englishId = english.getActionCommand();
            mathsId = mathematics.getActionCommand();
            scienceId = science.getActionCommand();
            historyId = history.getActionCommand();

            this.dispose();

        }
    }//GEN-LAST:event_buttonGradient4ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        subjectName(englishId);
        subjectName(mathsId);
        subjectName(scienceId);
        subjectName(historyId);
        subjectName(languageID);
        subjectName(religionId);
        subjectName(icategory);
        subjectName(iicategory);
        subjectName(iiicategory);

    }//GEN-LAST:event_formWindowClosed

    private void buttonGradient5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) student.getOlTable().getModel();
        model.setRowCount(0);
        this.dispose();
    }//GEN-LAST:event_buttonGradient5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aosinhala;
    private javax.swing.JCheckBox art;
    private SMMV.Component.Background background1;
    private SMMV.Component.Background background2;
    private SMMV.Component.Background background3;
    private SMMV.Component.Background background4;
    private javax.swing.JCheckBox buddist;
    private javax.swing.JCheckBox bussness;
    private SMMV.Component.ButtonGradient buttonGradient4;
    private SMMV.Component.ButtonGradient buttonGradient5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JCheckBox catholicm;
    private javax.swing.JCheckBox christianity;
    private javax.swing.JCheckBox civic;
    private javax.swing.JCheckBox danceb;
    private javax.swing.JCheckBox danceo;
    private javax.swing.JCheckBox drama;
    private javax.swing.JCheckBox economic;
    private javax.swing.JCheckBox english;
    private javax.swing.JCheckBox entrepreneurship;
    private javax.swing.JCheckBox french;
    private javax.swing.JCheckBox geogra;
    private javax.swing.JCheckBox germen;
    private javax.swing.JCheckBox health;
    private javax.swing.JCheckBox history;
    private javax.swing.JCheckBox ict;
    private javax.swing.JCheckBox islam;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox japan;
    private javax.swing.JCheckBox karean;
    private javax.swing.JCheckBox mathematics;
    private javax.swing.JCheckBox musico;
    private javax.swing.JCheckBox musicw;
    private javax.swing.JCheckBox pali;
    private javax.swing.JCheckBox saivanery;
    private javax.swing.JCheckBox sanskrit;
    private javax.swing.JCheckBox science;
    private javax.swing.JCheckBox second;
    private javax.swing.JCheckBox secont2;
    private javax.swing.JCheckBox sinhala;
    private javax.swing.JCheckBox tamil;
    // End of variables declaration//GEN-END:variables
}
